### ISSUE TITLE
S3 Bucket publish got failed while trying to upload ubuntu precise

### ISSUE THREAD

**Issue by PraveenJayakrishnakumar** [smira/aptly#301] opened 2015-09-10 01:05 UTC
We are trying to publish snapshot for ubuntu precise and precise-updates in s3 bucket. But unfortunately, we are not able to publish to s3 bucket. we are getting different error in every time.

Here are the some errors (that caused in everytime):

1. ERROR: unable to publish: unable to process packages: error getting information about ubuntu-repo/pool/main/g/git/git-doc_1.7.9.5-1_all.deb from S3: us-east-1:test-aptly/: 500 Internal Server Error

2. ERROR: unable to publish: unable to process packages: error uploading /opt/aptly/.aptly/pool/d1/be/linux-backports-modules-cw-3.4-3.2.0-60-virtual_3.2.0-60.50_amd64.deb to S3: us-east-1:test-aptly/: We encountered an internal error. Please try again.

3. ERROR: unable to publish: unable to process packages: error uploading /opt/aptly/.aptly/pool/cf/6d/libgd2-noxpm_2.0.36~rc1~dfsg-6ubuntu2_amd64.deb to S3: us-east-1:test-aptly/: We encountered an internal error. Please try again.

**Comment by smira** [comment] 2015-09-18 13:24
These all are S3 API errors, please try nightly build of aptly (https://www.aptly.info/download/).

Duplicate of #297

**Closed** 2015-09-18 13:24 UTC
Labels: duplicate
