### ISSUE TITLE
conflict in package on `mirror update`

### ISSUE THREAD

**Issue by paulczar** [smira/aptly#187] opened 2015-01-31 00:56 UTC
When trying to mirror precise or trusty from `packages.erlang-solutions.com/ubuntu/`

I get this error:

```
$ aptly mirror update erlang-precise
Downloading http://packages.erlang-solutions.com/ubuntu/dists/precise/InRelease...
Downloading http://packages.erlang-solutions.com/ubuntu/dists/precise/Release...
Downloading http://packages.erlang-solutions.com/ubuntu/dists/precise/Release.gpg...
gpgv: Signature made Thu 11 Dec 2014 06:46:05 AM CST using RSA key ID A14F4FCA
gpgv: Good signature from "Erlang Solutions Ltd. <packages@erlang-solutions.com>"
Downloading & parsing package files...
Downloading http://packages.erlang-solutions.com/ubuntu/dists/precise/contrib/binary-amd64/Packages.bz2...
ERROR: unable to update: conflict in package elixir_1.0.0-1_all
```

The -force-overwrite doesn't appear to be usable for the mirror commands and I'm not sure how to work around this.

**Comment by smira** [comment] 2015-01-31 17:57
@paulczar this seems to be exact duplicate of #183. I'll try to deal with it today and release nightly build.

**Closed by smira** 2015-01-31 17:57 UTC
Labels: duplicate
