### ISSUE TITLE
Mirror update repeats download exists file

### ISSUE THREAD

**Issue by MSI77** [smira/aptly#651] opened 2017-10-03 20:48 UTC
## Detailed Description
Always repeats download exist files after download error.

## Context
aptly mirror create -architectures="i386,amd64" -with-udebs=true xenial-main https://mirror.yandex.ru/ubuntu/ xenial main
aptly mirror update xenial-main

ERROR: unable to update: download errors:
  https://mirror.yandex.ru/ubuntu/pool/main/l/language-pack-gnome-mn/language-pack-gnome-mn_16.04+20160320_all.deb: unexpected EOF
  https://mirror.yandex.ru/ubuntu/pool/main/liba/libabw/libabw-0.1-1v5_0.1.1-2ubuntu2_i386.deb: unexpected EOF
  https://mirror.yandex.ru/ubuntu/pool/main/t/taglib/libtag1v5-vanilla_1.9.1-2.4ubuntu1_amd64.deb: unexpected EOF
  https://mirror.yandex.ru/ubuntu/pool/main/w/whoopsie-preferences/libwhoopsie-preferences-dev_0.18_i386.deb: Get https:/ubuntu/pool/main/w/whoopsie-preferences/libwhoopsie-preferences-dev_0.18_i386.deb: dial tcp 213.180.204.183:443: i/o timeout
  https://mirror.yandex.ru/ubuntu/pool/main/p/psycopg2/python-psycopg2-dbg_2.6.1-1build2_i386.deb: unexpected EOF
  https://mirror.yandex.ru/ubuntu/pool/main/liba/libassuan/libassuan-dev_2.4.2-2_amd64.deb: unexpected EOF

Always download full repo.

**Comment by erickeller** [comment] 2017-10-10 11:34
I suspect this is a duplicate of #641

**Comment by exaos** [comment] 2017-11-08 00:06
The same error here. After downloading ~80GB packages, `aptly mirror update` stopped with an "I/O timeout" error. Then, I restart the mirror updating and hope it will continue to finish the remaining downloading. Unfortunately, aptly starts to download from the scratch.
Aptly 1.1.1 on Archlinux.

**Comment by smira** [comment] 2017-11-08 20:30
Yep, I believe it's same as #641. I'll try to get it fixed for the next version

**Comment by danwerspb** [comment] 2017-11-15 20:22
I confirm this case.

**Comment by smira** [comment] 2017-11-30 21:30
Should be available now in nightly `aptly_1.1.1+75+g9cb2a30`

**Closed by smira** 2017-11-30 21:30 UTC
Labels: 1.2.0
