### ISSUE TITLE
Mirror of repository with only SHA sums produces error

### ISSUE THREAD

**Issue by marcusn** [smira/aptly#442] opened 2016-09-15 10:11 UTC
I am trying to mirror the Chef repository:

aptly mirror create -force-components -filter '' chef-trusty-main https://packages.chef.io/stable-apt trusty main

aptly mirror update chef-trusty-main
Downloading https://packages.chef.io/stable-apt/dists/trusty/InRelease...
Downloading https://packages.chef.io/stable-apt/dists/trusty/Release...
Downloading https://packages.chef.io/stable-apt/dists/trusty/Release.gpg...
gpgv: Signature made Wed 14 Sep 2016 06:34:36 PM UTC using DSA key ID 83EF826A
gpgv: Good signature from "CHEF Packages packages@chef.io"
gpgv:                 aka "Opscode Packages packages@opscode.com"
Downloading & parsing package files...
Downloading https://packages.chef.io/stable-apt/dists/trusty/main/binary-amd64/Packages.bz2...
Building download queue...
ERROR: unable to update: unable to compute pool location for filename chef_12.3.0-1_amd64.deb, MD5 is missing

It seems that the Packages.bz2 does not contain MD5sum, but they do contain SHA sums..

**Comment by camelpunch** [comment] 2016-10-03 14:04
Dupe of https://github.com/smira/aptly/issues/228

**Comment by smira** [comment] 2017-03-30 22:01
Closing as duplicate.

**Closed by smira** 2017-03-30 22:01 UTC
Labels: 1.1.0-Maybe
