### ISSUE TITLE
S3 Publishing Large Repos

### ISSUE THREAD

**Issue by mattford63** [smira/aptly#297] opened 2015-09-04 17:06 UTC
When publishing large mirrors to S3 I quickly hit the S3 API throttling limits.

Aptly doesn't seem to gracefully scale down (boto based stuff does) and simply fails the publish instead.

My working theory is the many HEAD requests to check file existence happen quickly enough to cause issues.

To re-create try to upload, say, trusty-updates to s3.

I've tried rate limiting with IPTables and the user space throttler trickle.  Too not much success.  I'd love to see if others have seen this issue?

**Comment by mattford63** [comment] 2015-09-04 17:08
Hmmmm - I've looked at the code now (apologies should have done that first).

There does seem to be back-off included

https://github.com/smira/aptly/blob/master/s3/retry.go

**Comment by mattford63** [comment] 2015-09-04 17:54
I'll try with a nightly build to see if that does better with the fairly recently introduced s3 retry code.

**Comment by mattford63** [comment] 2015-09-04 18:33
So a nightly build seemed to fix the issue but the throttling is not smooth - it's very fast until throttled and then pretty much all transfers are stopped.  Then it seems to sporadically start/stop for a whilst.

**Comment by mattford63** [comment] 2015-09-08 13:00
Rather than S3 throttling (that seems resovlved) I hit the following type issue

```
ERROR: unable to publish: unable to process packages: error uploading /mnt/aptly/root/pool/
69/d9/firefox-testsuite_28.0+build2-0ubuntu2_amd64.deb to S3: us-east-1:cnry-aptrepo/: Put 
https:/cnry-aptrepo/trusty-universe/pool/dev/f/firefox/firefox-testsuite_28.0%2Bbuild2-0ubu
ntu2_amd64.deb: http: ContentLength=250603492 with Body length 210218024                  
Could not publish trusty-universe-201509081042
```

A rerun get's things going again only to stop again at a different upload a good whilst later.

**Comment by smira** [comment] 2015-09-14 12:18
@mattford63 what do you mean by throttling? aptly might seem faster at the start, as it doesn't re-upload files to S3 if they're already present - check for the file is much faster.

Second error with Content-Length/Body-Length mismatch seems to be one of the issues with the new version of S3 library. I need to look into that.

**Comment by mattford63** [comment] 2015-09-16 08:16
HI @smira, by throttling I mean that the HEAD requests that check for existence easily outstrip the rate of calls the S3 API allows you to do.  However the nightly build seems to have back-off code in.

**Comment by mdxp** [comment] 2015-09-24 01:19
I'm having similar issues and unable to complete a publish to s3. I'm using the latest nightly package and have errors like this:

```
ERROR: unable to publish: unable to process packages: error uploading 
/srv/aptly/pool/bd/64/libfreefoam1_0.1.0+dfsg+1-3_amd64.deb to S3: us-west-2:apt-dev-tt/: Put
https:/apt-dev.tt/pool/main/f/freefoam/libfreefoam1_0.1.0%20dfsg%201-3_amd64.deb: EOF
```
or

```
ERROR: unable to publish: unable to process packages: error uploading 
/srv/aptly/pool/5f/82/libmessage-passing-filter-regexp-perl_0.05-1_all.deb to S3: 
us-west-2:apt-dev.tt/: Put https:/apt-dev.tt/pool/main/libm/libmessage-passing-filter-regexp-
perl/libmessage-passing-filter-regexp-perl_0.05-1_all.deb: http: ContentLength=15524 
with Body length 0 
```

**Comment by smira** [comment] 2015-09-24 19:01
I was able to reproduce some EOFs as well. Probably we need more aggressive retry (I will look into that). Anyway restarting `publish` command should be safe.

**Comment by mdxp** [comment] 2015-09-24 20:02
I would be great if when restarting a `publish` command it will remember where it crashed and re-start from there (like mirror update). Unfortunately for a debian/ubuntu mirror of +50GB even to do the HEAD checks on the files it will take more than 30-40mins to catchup to where it broke.

**Comment by smira** [comment] 2015-09-24 20:39
@mdxp one option is to speed up "file exists" checks (HEAD requests) by issuing "List request" and collecting all entries under the prefix... It might depend on the workload, but should be significantly faster

**Comment by mdxp** [comment] 2015-09-25 00:30
That would be awesome!

**Comment by smira** [comment] 2015-10-01 11:07
@mdxp latest nightly build `aptly_0.9.6~dev+150+ga294a91` should contain fix to use listing instead of multiple get requests... please give it a try!

**Comment by mdxp** [comment] 2015-10-03 02:06
OMG @smira this is awesome. I just tried it out and it is amazingly fast; I'm sure that anyone that's using aptly with S3 will love this. I tested various scenarios and it worked out great. Unrelated from this I've found a bug (that was always there from what I can tell), the 'file exist' check will not verify for `plusWorkaround` type of packages (if enabled), and just ignore those.

**Comment by jmo-learnosity** [comment] 2015-10-04 03:27
I agree with @mdxp that this is much quicker now. I am hitting a problem, though, using the latest nightly when doing a `publish switch` to S3 where, on a machine with over a GB of RAM free, I run out of memory with the following error:

```
$ aptly version
aptly version: 0.9.6~dev
$ aptly publish switch -passphrase=supersecret trusty-security s3:my-aptly-mirror:ubuntu-security ubuntu-security_trusty-security-20151004
Loading packages...
Generating metadata files and linking package files...
panic: unable to unxz: fork/exec /usr/bin/xz: cannot allocate memory [recovered]
        panic: unable to unxz: fork/exec /usr/bin/xz: cannot allocate memory

goroutine 1 [running]:
github.com/smira/aptly/cmd.Run.func1(0xc824f33f18)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/cmd/run.go:16 +0x7f
github.com/smira/aptly/deb.(*Package).CalculateContents(0xc82045efc0, 0x7f082a491468, 0xc8201050e0, 0x0, 0x0, 0x0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/package.go:433 +0x1b4
github.com/smira/aptly/deb.(*PackageCollection).loadContents(0xc8201055e0, 0xc82045efc0, 0x7f082a491468, 0xc8201050e0, 0x0, 0x0, 0x0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/package_collection.go:183 +0x37b
github.com/smira/aptly/deb.(*Package).Contents(0xc82045efc0, 0x7f082a491468, 0xc8201050e0, 0x0, 0x0, 0x0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/package.go:413 +0xfa
github.com/smira/aptly/deb.(*ContentsIndex).Push(0xc82052e080, 0xc82045efc0, 0x7f082a491468, 0xc8201050e0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/contents.go:26 +0x4a
github.com/smira/aptly/deb.(*PublishedRepo).Publish.func1(0xc82045efc0, 0x0, 0x0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/publish.go:567 +0x8d5
github.com/smira/aptly/deb.(*PackageList).ForEachIndexed(0xc8203fa750, 0xc824f33640, 0x0, 0x0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/list.go:139 +0xed
github.com/smira/aptly/deb.(*PublishedRepo).Publish(0xc820169380, 0x7f082a491468, 0xc8201050e0, 0x7f082a491520, 0xc8200d33f0, 0xc82015df80, 0x7f082a491410, 0xc8203e7620, 0x7f082a4914b0, 0xc8203fa1e0, ...)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/deb/publish.go:592 +0x1135
github.com/smira/aptly/cmd.aptlyPublishSwitch(0xc8201605a0, 0xc820072d40, 0x3, 0x3, 0x0, 0x0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/cmd/publish_switch.go:97 +0x12ba
github.com/smira/commander.(*Command).Dispatch(0xc8201605a0, 0xc820072d40, 0x3, 0x3, 0x0, 0x0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:305 +0x647
github.com/smira/commander.(*Command).Dispatch(0xc8201607e0, 0xc820072d30, 0x4, 0x4, 0x0, 0x0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x1f0
github.com/smira/commander.(*Command).Dispatch(0xc820160fc0, 0xc820072d20, 0x5, 0x5, 0x0, 0x0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/smira/commander/commands.go:283 +0x1f0
github.com/smira/aptly/cmd.Run(0xc820160fc0, 0xc82000a0f0, 0x6, 0x6, 0xc3dd01, 0x0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/cmd/run.go:40 +0x19a
main.main()
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/main.go:9 +0x73

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/smira/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 6 [syscall]:
os/signal.loop()
        /home/smira/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /home/smira/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [runnable]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc82014a1c0)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x29d
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x26b

goroutine 28 [sleep]:
time.Sleep(0xbebc200)
        /home/smira/.gvm/gos/go1.5/src/runtime/time.go:59 +0xf9
github.com/cheggaaa/pb.(*ProgressBar).writer(0xc820baa780)
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/cheggaaa/pb/pb.go:332 +0x5b
created by github.com/cheggaaa/pb.(*ProgressBar).Start
        /home/smira/.gvm/pkgsets/go1.5/global/src/github.com/smira/aptly/_vendor/src/github.com/cheggaaa/pb/pb.go:101 +0x9c
```

**Comment by smira** [comment] 2015-10-04 15:16
@mdxp yep, `plusWorkaround` files are considered to be "mirrors" of normal files, so if normal file exists, it is considered that plusWorkaround file exists as well...

**Comment by smira** [comment] 2015-10-04 15:17
@jmo-learnosity this seems to be different issue - both contents generation and S3 publishing need some memory... What is the repository size? aptly could be memory-hungry

**Comment by jmo-learnosity** [comment] 2015-10-05 02:00
@smira I wasn't sure whether or not to create another issue for what I was seeing as this is an issue I am only hitting while publishing large repositories. I've only hit this issue since the change to use `ListObjects` was made. This is the output showing the size of one of the snapshots that produces an out of memory error:
```
$ aptly snapshot show ubuntu-security_trusty-security-20151004
Name: ubuntu-security_trusty-security-20151004
Created At: 2015-10-04 02:09:16 UTC
Description: Merged from sources: 'ubuntu-security_trusty-security_main-20151004', 'ubuntu-security_trusty-security_universe-20151004'
Number of packages: 5074
```
It seems to panic about half way through the publishing process of this repository.

**Comment by jmo-learnosity** [comment] 2015-10-05 02:46
Just doing some more playing with this and have increased the memory available to the machine from 2 to 4GB and I am still having publishes to S3 bomb out due to running out of memory.

It seems to use quite a lot of memory when skipping through the files that have already been uploaded to an S3 bucket when, presumably, it isn't actually uploading anything.

**Comment by mdxp** [comment] 2015-10-05 16:44
@jmo-learnosity I'm mirroring debian jessie (+60GB), and I just looked at the memory consumption and it is about 2GB per process/run on publish switch. My machine has 15G RAM as I am using a bigger instance for better network performance and not be limited by that; I haven't even looked at the memory consumption before and it never crashed for me because of that. Still, it is still crashing many times with timeouts and other such errors.

**Comment by smira** [comment] 2016-02-09 09:02
#344 is merged, which switches to official AWS Go SDK

**Comment by david-gregory-inmar** [comment] 2016-02-10 13:22
For the first time I was able to publish snapshots of my two largest mirrors to S3 last night.  I'd say this is a very good sign that the new SDK may have resolved this issue...

**Comment by smira** [comment] 2016-02-10 14:17
Ok, this sound really promising!

**Closed by smira** 2016-02-10 14:17 UTC
Labels: bug

**Comment by mbugeia** [comment] 2016-02-16 10:20
Hi, do you plan to make a release with this fix soon ? I encounter the same error (EOF or ContentLength=xxx with Body length 0 ) with a not very large repo (~2GB).
Thanks

**Comment by smira** [comment] 2016-02-16 12:34
@mbugeia you can try with nightly build (fix is already there).

**Comment by mbugeia** [comment] 2016-02-16 15:43
@smira Thanks but is the nightly stable enough ? Will I be able to rollback easily if that's not the case ?

**Comment by smira** [comment] 2016-02-16 16:02
@mbugeia current nightly is almost 0.9.6 + S3 fix. It should be stable, and you can roll back to 0.9.6 by simply upgrading/downgrading package.

**Comment by mdxp** [comment] 2016-02-16 16:04
@mbugeia I've been running nightly build `0.9.6~dev+156+g339bf0a` for several weeks without any problems. Like @smira said it should be safe to use and you can always go back to 0.9.6.

**Comment by mbugeia** [comment] 2016-02-16 16:06
Cool thank you both, I will test it and give you a feedback.

**Comment by mbugeia** [comment] 2016-02-17 09:56
I confirm that everything works fine with the nightly. Thanks !
